### ISSUE TITLE
It crashed.

### ISSUE THREAD

**Issue by sankooki** [smka/homebridge-broadlink-sp#1]
Hi,

I run this plugin, then produced this error message.

I got one sp3, two rm mini3.

Thank you.

Apr 19 15:29:50 raspberrypi homebridge[4590]: /usr/lib/node_modules/homebridge-broadlink-sp/index.js:36
Apr 19 15:29:50 raspberrypi homebridge[4590]: dev.check_power();
Apr 19 15:29:50 raspberrypi homebridge[4590]: ^
Apr 19 15:29:50 raspberrypi homebridge[4590]: TypeError: dev.check_power is not a function
Apr 19 15:29:50 raspberrypi homebridge[4590]: at module.exports.b.on (/usr/lib/node_modules/homebridge-broadlink-sp/index.js:36:13)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at emitOne (events.js:96:13)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at module.exports.emit (events.js:191:7)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at device.dev.on (/usr/lib/node_modules/homebridge-broadlink-sp/node_modules/broadlinkjs-sm/index.js:182:48)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at emitNone (events.js:86:13)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at device.emit (events.js:188:7)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-sp/node_modules/broadlinkjs-sm/index.js:243:18)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at emitTwo (events.js:106:13)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at Socket.emit (events.js:194:7)
Apr 19 15:29:50 raspberrypi homebridge[4590]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
Apr 19 15:29:50 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Apr 19 15:29:50 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by smka** [comment]
Hi!
I've updated some stuff. It seem your RM device was found first, now it should find only SP.
Please, install plugin again, i
`sudo npm install -g homebridge-broadlink-sp`

I've tested only with one SP3 device in network, and don't know how it works with more then one. I'll test it this week.

**Comment by sankooki** [comment]
Thank you but another error message.

/usr/lib/node_modules/homebridge-broadlink-sp/node_modules/broadlinkjs-sm/index.js:100
Apr 20 01:01:43 raspberrypi homebridge[10163]: dev.device();
Apr 20 01:01:43 raspberrypi homebridge[10163]: ^
Apr 20 01:01:43 raspberrypi homebridge[10163]: TypeError: dev.device is not a function
Apr 20 01:01:43 raspberrypi homebridge[10163]: at module.exports.Broadlink.genDevice (/usr/lib/node_modules/homebridge-broadlink-sp/node_modules/broa
Apr 20 01:01:43 raspberrypi homebridge[10163]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-sp/node_modules/broadlinkjs-sm/index.js:18
Apr 20 01:01:43 raspberrypi homebridge[10163]: at emitTwo (events.js:106:13)
Apr 20 01:01:43 raspberrypi homebridge[10163]: at Socket.emit (events.js:194:7)
Apr 20 01:01:43 raspberrypi homebridge[10163]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
Apr 20 01:01:43 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Apr 20 01:01:43 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by smka** [comment]
Okey, i've updated plugin for use with multiple devices.
Now you need to set your SP IP address in homebridge config.json (see config-sample.json).

1. update plugin 
`sudo npm update -g homebridge-broadlink-sp`
2. update your config.json and add ip of your SP

**Comment by sankooki** [comment]
wow,

It's doing great. Thanks a lot.
