### ISSUE TITLE
MP1 Support

### ISSUE THREAD

**Issue by nitaybz** [smka/homebridge-broadlink-sp#3]
Hey Man, Great job creating this plugin! I found it very useful.
any chance you can add Broadlink MP1 support to this plugin? that would be much appreciated...

**Comment by smka** [comment]
Hello! I think I can add MP1 support, but I don't have it for testing. 
Without device it will be very complicated.

**Comment by nitaybz** [comment]
I would happily test and debug for you!!
Anything you need to make it happen.

**Comment by smka** [comment]
@nitaybz ok lets try... i hope you have nodejs installed.

1. get last broadlinkjs-sm from dev branch: https://github.com/smka/broadlinkjs-sm/archive/dev.zip
2. unzip and go to test folder
3. run mp_check.js script `node mp_check.js` (it should print all 4 strip status, then turn on s1, check all strips again, and turn off s1)

please, copy all log here with errors (i think they should be)))).

**Comment by nitaybz** [comment]
I installed the repo on my pi and did it from there... this is the log:

```
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$ node mp_check.js
MP1 found..
/usr/lib/node_modules/broadlinkjs-sm/index.js:360
    this.prototype.set_power_mask = function(sid_mask, state) {
                                  ^

TypeError: Cannot set property 'set_power_mask' of undefined
    at device.mp1 (/usr/lib/node_modules/broadlinkjs-sm/index.js:360:35)
    at module.exports.Broadlink.genDevice (/usr/lib/node_modules/broadlinkjs-sm/index.js:97:13)
    at Socket.cs.on (/usr/lib/node_modules/broadlinkjs-sm/index.js:189:28)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:194:7)
    at UDP.onMessage [as onmessage] (dgram.js:545:8)
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$
```
let's keep going... 

Thanks!

**Comment by nitaybz** [comment]
I removed the word `prototype` from line 360 and it seems like it works perfectly!! this is the log:


```
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$ node mp_check.js
MP1 found..
SP2@10.0.0.3 found... not MP1!
check power...
case default -
s1 power is on false
s2 power is on false
s3 power is on true
s4 power is on true
Unknown@10.0.0.2 found... not MP1!
Unknown@10.0.0.4 found... not MP1!
power s1 ON...
case default -
s1 power is on true
s2 power is on false
s3 power is on true
s4 power is on true
case default -
s1 power is on true
s2 power is on false
s3 power is on true
s4 power is on true
power s1 OFF...
case default -
s1 power is on false
s2 power is on false
s3 power is on true
s4 power is on true
```

Man, you rock!
I just checked with all the sockets trying to turn them on and off and it always show the right value, true for ON and false for OFF...
it's time to implement in the plugin :)

**Comment by smka** [comment]
yeah! cool! please, download dev branch again and show me the log.
I wonder in what case sockets are checking.

I'll think about plugin tomorrow. I don't know how to implement it better. Should I update this one, or create a new one for MP1 device only?

**Comment by nitaybz** [comment]
don't know what this means but here is the log:

```
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$ node mp_check.js
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at startup (bootstrap_node.js:125:32)
    at bootstrap_node.js:538:3

```

I think it should be on a different plugin  - homebridge-broadlink-mp.
automatically ads 4 sockets accessory to homebridge... and maybe it will be possible to edit the names on the config... you might need to do it as a platform since there are 4 accessories in it.
Thanks!

**Comment by smka** [comment]
I think you run mp_check that doesn't exist in test folder.   Are you sure you have downloaded the right dev branch from the link above?

**Comment by nitaybz** [comment]
you are right... here is the new log:

```
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$ node mp_check.js
MP1 found..
Unknown@10.0.0.2 found... not MP1!
Unknown@10.0.0.4 found... not MP1!
check power...
SP2@10.0.0.3 found... not MP1!
case default - 14
case value - 14
s1 power is on false
s2 power is on false
s3 power is on false
s4 power is on false
power s1 ON...
case default - 14
case value - 14
s1 power is on true
s2 power is on false
s3 power is on false
s4 power is on false
case default - 14
case value - 14
s1 power is on true
s2 power is on false
s3 power is on false
s4 power is on false
power s1 OFF...
case default - 14
case value - 14
s1 power is on false
s2 power is on false
s3 power is on false
s4 power is on false
homebridge@raspberrypi:/usr/lib/node_modules/broadlinkjs-sm/test$
```

**Comment by smka** [comment]
@nitaybz thanks. It's interesting... after set socket power on/off check_power always triggered.
It's not a problem, but I should think about it.
I'll try to make homebridge-broadlink-mp and you should test it with homebridge-broadlink-sp together.

**Comment by nitaybz** [comment]
I will! cause I do have an SP2 as well... bring it on

**Comment by nitaybz** [comment]
@smka how's it going?

**Comment by smka** [comment]
@nitaybz hi! i'm working on the one platform for sp and mp devices. it's almost done.

**Comment by nitaybz** [comment]
I'm very excited! let me know when can I test it

**Comment by smka** [comment]
@nitaybz i saw you did your mp platform version. Did you test it? Works fine?

**Comment by nitaybz** [comment]
0I tried to do it myself but to be honest I failed...
I could control the switches and I could check their status, but it never worked well...
I think that when  I did each socket as an accessory in the platform it crashed or took too long to get a reply from the device.

sometimes I would see only some of the sockets checking for the status, I guess that it stuck so it didn't check for the others.

in the Home app usually I saw it keeps loading all the devices on that bridge (pi) as you probably know, when one device is pending for status usually the whole bridge will not report status until that device return it...

so it basically it didn't work well... also I noticed that when I did saw it in Home app I could only change the On/Off button when I waited a few seconds between changing the switch, when I did it immediately it made the system stuck.

I believe the best way to handle it would be to get one request for all the sockets... but that's for you to fix, I gave up, spent a lot of time on it.

**Comment by smka** [comment]
@nitaybz hi! yes i know this problems, i'm trying to figure it out. 
Please try [this version](https://github.com/smka/homebridge-broadlink-mp) with MP and SP devices (and remove broadlinkSP accessories from config.json when test mp plugin)

If MP even work, then I'll try to fix long response.

**Comment by nitaybz** [comment]
I encountered the same issue as with my fork... The MP1 does not return state and therefor makes the home app stuck... I succeeded turning on the SP2 but not turning it off...
check the log when I made the system crush by clicking the accessories on the app:

```
[5/12/2017, 8:41:51 AM] check power for MP1s1 s1
May 12 08:41:51 raspberrypi homebridge[11159]: /usr/lib/node_modules/homebridge-broadlink-mp/index.js:190
May 12 08:41:51 raspberrypi homebridge[11159]: dev.check_power();
May 12 08:41:51 raspberrypi homebridge[11159]: ^
May 12 08:41:51 raspberrypi homebridge[11159]: TypeError: dev.check_power is not a function
May 12 08:41:51 raspberrypi homebridge[11159]: at module.exports.b.on (/usr/lib/node_modules/homebridge-broadlink-mp/index.js:190:21)
May 12 08:41:51 raspberrypi homebridge[11159]: at emitOne (events.js:96:13)
May 12 08:41:51 raspberrypi homebridge[11159]: at module.exports.emit (events.js:191:7)
May 12 08:41:51 raspberrypi homebridge[11159]: at device.dev.on (/usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:190:48)
May 12 08:41:51 raspberrypi homebridge[11159]: at emitNone (events.js:86:13)
May 12 08:41:51 raspberrypi homebridge[11159]: at device.emit (events.js:188:7)
May 12 08:41:51 raspberrypi homebridge[11159]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:251:18)
May 12 08:41:51 raspberrypi homebridge[11159]: at emitTwo (events.js:106:13)
May 12 08:41:51 raspberrypi homebridge[11159]: at Socket.emit (events.js:194:7)
May 12 08:41:51 raspberrypi homebridge[11159]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
May 12 08:41:51 raspberrypi flicd[760]: Client EOF
```

**Comment by smka** [comment]
@nitaybz please get new [homebridge-broadlink-mp](https://github.com/smka/homebridge-broadlink-mp) and install it. Now it'll download dependency from my dev branch. May be it'll work.
You should see after install
homebridge-broadlink-mp@0.0.1 \
└── broadlinkjs-sm@0.1.**4**

**Comment by nitaybz** [comment]
I did what you said and saw it update to 0.1.4

here is the new log error:
```
May 12 11:23:04 raspberrypi homebridge[13286]: unknown device found... dev_type: 2737
May 12 11:23:04 raspberrypi homebridge[13286]: /usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:191
May 12 11:23:04 raspberrypi homebridge[13286]: dev.on("deviceReady", () => { this.emit("deviceReady", dev); });
May 12 11:23:04 raspberrypi homebridge[13286]: ^
May 12 11:23:04 raspberrypi homebridge[13286]: TypeError: Cannot read property 'on' of undefined
May 12 11:23:04 raspberrypi homebridge[13286]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:191:16)
May 12 11:23:04 raspberrypi homebridge[13286]: at emitTwo (events.js:106:13)
May 12 11:23:04 raspberrypi homebridge[13286]: at Socket.emit (events.js:194:7)
May 12 11:23:04 raspberrypi homebridge[13286]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
```

**Comment by smka** [comment]
@nitaybz 2737 device type is RM-mini. Do you have it in your network? 
I wonder how does it pass ip or mac filter? Are you sure you have correct ip or mac address for MP device type in config.json?

**Comment by nitaybz** [comment]
I do have an RM-Mini in the system... but not on that IP...
this is my config:
```
 {
            "platform": "broadlinkMP",
            "accessories": [{
                    "name": "SP2",
                    "type": "SP",
                    "ip": "X.0.0.3"
                },
                {
                    "name": "MP1",
                    "type": "MP",
                    "ip": "X.0.0.15"
                }
            ]
        },
```

that IP X.0.0.15 has the MP1 installed... the RM mini is on different IP, I also have RM Pro on the network

**Comment by nitaybz** [comment]
I also got another log error same as the first one but with different Dev Type: 272a

**Comment by smka** [comment]
please update homebridge-broadlink-mp 
`(sudo) npm update` 
to update dependency - i added debug log

**Comment by nitaybz** [comment]
```
May 12 12:53:48 raspberrypi homebridge[14883]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 12:53:48 raspberrypi homebridge[14883]: /usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:191
May 12 12:53:48 raspberrypi homebridge[14883]: dev.on("deviceReady", () => { this.emit("deviceReady", dev); });
May 12 12:53:48 raspberrypi homebridge[14883]: ^
May 12 12:53:48 raspberrypi homebridge[14883]: TypeError: Cannot read property 'on' of null
May 12 12:53:48 raspberrypi homebridge[14883]: at Socket.cs.on (/usr/lib/node_modules/homebridge-broadlink-mp/node_modules/broadlinkjs-sm/index.js:191:16)
May 12 12:53:48 raspberrypi homebridge[14883]: at emitTwo (events.js:106:13)
May 12 12:53:48 raspberrypi homebridge[14883]: at Socket.emit (events.js:194:7)
May 12 12:53:48 raspberrypi homebridge[14883]: at UDP.onMessage [as onmessage] (dgram.js:545:8)
```

**Comment by nitaybz** [comment]
this is recognizing the RM Pro....
I even try to replace the IP with a mac address

**Comment by smka** [comment]
and one more time update plz! I've pushed fix.

**Comment by nitaybz** [comment]
we are close...
Homebridge has loaded, the Home App is stuck on "Updating" for all the accessories, but once it shows the status "No Response" on each accessory I can click on the s1 - s4 accessories and their status show. I could even control the s1 but than when I tried to control s2 it all got messy, nor can I  set any of them on or off, it's just thinking(loading) for ever.
here is the recent log:

```
May 12 13:03:59 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:03:59 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:03:59 raspberrypi homebridge[15657]: [5/12/2017, 1:03:59 PM] check power for MP1s1 s1
May 12 13:03:59 raspberrypi homebridge[15657]: [5/12/2017, 1:03:59 PM] device type:MP1 @ 10.0.0.15
May 12 13:04:06 raspberrypi homebridge[15657]: [5/12/2017, 1:04:06 PM] set s1 state to 1
May 12 13:04:07 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:07 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:07 raspberrypi homebridge[15657]: [5/12/2017, 1:04:07 PM] ON!
May 12 13:04:08 raspberrypi homebridge[15657]: [5/12/2017, 1:04:08 PM] set s1 state to 0
May 12 13:04:08 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:08 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:08 raspberrypi homebridge[15657]: [5/12/2017, 1:04:08 PM] OFF!
May 12 13:04:09 raspberrypi homebridge[15657]: [5/12/2017, 1:04:09 PM] set s1 state to 1
May 12 13:04:09 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:09 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:09 raspberrypi homebridge[15657]: [5/12/2017, 1:04:09 PM] ON!
May 12 13:04:10 raspberrypi homebridge[15657]: [5/12/2017, 1:04:10 PM] set s1 state to 0
May 12 13:04:11 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:11 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:11 raspberrypi homebridge[15657]: [5/12/2017, 1:04:11 PM] OFF!
May 12 13:04:12 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:12 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:12 raspberrypi homebridge[15657]: [5/12/2017, 1:04:12 PM] check power for MP1s2 s2
May 12 13:04:12 raspberrypi homebridge[15657]: [5/12/2017, 1:04:12 PM] device type:MP1 @ 10.0.0.15
May 12 13:04:13 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:13 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:13 raspberrypi homebridge[15657]: [5/12/2017, 1:04:13 PM] check power for MP1s3 s3
May 12 13:04:13 raspberrypi homebridge[15657]: [5/12/2017, 1:04:13 PM] device type:MP1 @ 10.0.0.15
May 12 13:04:14 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:14 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:14 raspberrypi homebridge[15657]: [5/12/2017, 1:04:14 PM] check power for MP1s4 s4
May 12 13:04:14 raspberrypi homebridge[15657]: [5/12/2017, 1:04:14 PM] device type:MP1 @ 10.0.0.15
May 12 13:04:18 raspberrypi homebridge[15657]: [5/12/2017, 1:04:18 PM] set s1 state to 1
May 12 13:04:18 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:18 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:18 raspberrypi homebridge[15657]: [5/12/2017, 1:04:18 PM] ON!
May 12 13:04:19 raspberrypi homebridge[15657]: [5/12/2017, 1:04:19 PM] set s1 state to 0
May 12 13:04:20 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:20 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
May 12 13:04:20 raspberrypi homebridge[15657]: [5/12/2017, 1:04:20 PM] OFF!
May 12 13:04:21 raspberrypi homebridge[15657]: [5/12/2017, 1:04:21 PM] set s2 state to 1
May 12 13:04:21 raspberrypi homebridge[15657]: unknown device found... dev_type: 272a @ 10.0.0.4
May 12 13:04:21 raspberrypi homebridge[15657]: unknown device found... dev_type: 2737 @ 10.0.0.2
```

**Comment by nitaybz** [comment]
feel free to make me reinstall and try... I will help you until we solve it

Update: I did manage to control the s2 also but it's like overloading the system when too many calls are being made.... it feels like if one of the switches is working I can turn it on and off freely, but when I try for another socket it will encounter and issue

**Comment by smka** [comment]
@nitaybz update it, i removed unnecessary debug and add some fix. I hope it'll help.

**Comment by nitaybz** [comment]
it's working well as long as you are not using 2 or 3 commands from different accessories one after the other.... it also affect the first load of homebridge when all 4 devices are calling for state, none of them return one and nothing is logged.
again, only after the "No Response" status show on Home App, then I can click on the required accessory (s1-s4) and get his status, and also turn it on and off. after playing with a few clicks on a few sockets I get the same issue where it's loading long time and then "No Response".

**Comment by nitaybz** [comment]
I think that if you feel stuck and want to debug the problem you have to print more logs in the broadlinkjs-sm library, it's interesting to check when the emit for mp_power, how long does it takes and if it always happen, and maybe it happens more than once and it needs to be handled.
another way to attach this issue is to make a different delay between the different sockets, the first socket that reply an answer will be store the data in a file or ram memory, the other socket accessories who wish to retrieve status can retrieve it from the memory if not more than a second or two has passed, that way they won't  need to call the device for each socket.
hope it helped...

**Comment by nitaybz** [comment]
I just realized that even the SP in the MP platform not always read the results, when I look at the logs I see that when the home App is loading("Updating" status), the only accessory that didn't retrieve status every time is the SP2.

**Comment by nitaybz** [comment]
@smka you gave up?

**Comment by smka** [comment]
@nitaybz  no, just weekends ) i understand the problem, and will try to fix it.

**Comment by nitaybz** [comment]
@smka I did a lot of work in the past few hours... you can see it in my fork, I was trying to keep a global status for discovering, making sure that when one accessory is discovering, the others will wait until the first one finished... I find it solving the get status problem...
but I noticed another problem, since I added a lot of logs I could see, that the library broadlinkjs-sm, not always discovering the device, I mean, that it's not always getting the "deviceReady" back and therefor make it stuck....

**Comment by nitaybz** [comment]
SOLVED!!!!
I found an easy way to solve that issue... when i found that `b.discover()` not always detecting the MP1 or the SP,  I decided (after a lot of false tries with complicated ways) to add more scans with an interval, I added:
```
var checkAgain = setInterval(function(){
                    self.log("Discovering Again for Set Command... " + self.sname);
                    b.discover();
                }, 1000)
```
with a `clearInterval(checkAgain)` after detecting the required device.

that totally did the trick! I can see in the logs that some times it require more than one scan to find the device.
I'll clean up my code and make a pull request...

**Comment by smka** [comment]
@nitaybz so now MP & SP devices works fine together?

**Comment by nitaybz** [comment]
Done, now you need to upload to npm... maybe update the name of the repo since it's SP & MP?

**Comment by nitaybz** [comment]
They work perfectly together!

**Comment by nitaybz** [comment]
next step would be to support S1C Security devices... that would allow a security device and a lot of sensors for cheap price :)

**Comment by smka** [comment]
@nitaybz thank you!

1. repo renamed - [homebridge-broadlink-platform](https://github.com/smka/homebridge-broadlink-platform)
2. published to [nmp](https://www.npmjs.com/package/homebridge-broadlink-platform)
3. i think we should close this issue and continue in new one @ homebridge-broadlink-platform
